"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.filesToWrite = [
    {
        name: '.gitignore',
        data: "\n# Created by https://www.gitignore.io/api/osx,node\n# Edit at https://www.gitignore.io/?templates=osx,node\n\n### Node ###\n# Logs\nlogs\n*.log\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n\n# Runtime data\npids\n*.pid\n*.seed\n*.pid.lock\n\n# Directory for instrumented libs generated by jscoverage/JSCover\nlib-cov\n\n# Coverage directory used by tools like istanbul\ncoverage\n\n# nyc test coverage\n.nyc_output\n\n# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)\n.grunt\n\n# Bower dependency directory (https://bower.io/)\nbower_components\n\n# node-waf configuration\n.lock-wscript\n\n# Compiled binary addons (https://nodejs.org/api/addons.html)\nbuild/Release\n\n# Dependency directories\nnode_modules/\njspm_packages/\n\n# TypeScript v1 declaration files\ntypings/\n\n# Optional npm cache directory\n.npm\n\n# Optional eslint cache\n.eslintcache\n\n# Optional REPL history\n.node_repl_history\n\n# Output of 'npm pack'\n*.tgz\n\n# Yarn Integrity file\n.yarn-integrity\n\n# dotenv environment variables file\n.env\n.env.test\n\n# parcel-bundler cache (https://parceljs.org/)\n.cache\n\n# next.js build output\n.next\n\n# nuxt.js build output\n.nuxt\n\n# vuepress build output\n.vuepress/dist\n\n# Serverless directories\n.serverless/\n\n# FuseBox cache\n.fusebox/\n\n# DynamoDB Local files\n.dynamodb/\n\n### OSX ###\n# General\n.DS_Store\n.AppleDouble\n.LSOverride\n\n# Icon must end with two \r\nIcon\n\n# Thumbnails\n._*\n\n# Files that might appear in the root of a volume\n.DocumentRevisions-V100\n.fseventsd\n.Spotlight-V100\nB\n.TemporaryItems\n.Trashes\n.VolumeIcon.icns\n.com.apple.timemachine.donotpresent\n\n# Directories potentially created on remote AFP share\n.AppleDB\n.AppleDesktop\nNetwork Trash Folder\nTemporary Items\n.apdisk\n\n# \n"
    },
    {
        name: 'package.json',
        data: "\n{\n  \"name\": \"example\",\n  \"version\": \"1.0.0\",\n  \"main\": \"./lib/index.js\",\n  \"bin\": {\n    \"example\": \"./lib/index.js\"\n  },\n  \"license\": \"MIT\"\n}\n"
    },
    {
        name: 'tsconfig.json',
        data: "\n{\n\t\"compilerOptions\": {\n\t\t\"target\": \"es5\",\n\t\t\"module\": \"commonjs\",\n\t\t\"lib\": [\"es6\", \"es2015\", \"dom\"],\n\t\t\"declaration\": true,\n\t\t\"outDir\": \"lib\",\n\t\t\"rootDir\": \"src\",\n\t\t\"strict\": true,\n\t\t\"types\": [\"node\"],\n\t\t\"esModuleInterop\": true,\n\t\t\"resolveJsonModule\": true\n\t}\n}\n"
    }
];
