"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.filesToWrite = [
    {
        name: '.gitignore',
        data: "# Created by https://www.gitignore.io/api/osx,node\n# Edit at https://www.gitignore.io/?templates=osx,node\n\n### Node ###\n# Logs\nlogs\n*.log\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n\n# Runtime data\npids\n*.pid\n*.seed\n*.pid.lock\n\n# Directory for instrumented libs generated by jscoverage/JSCover\nlib-cov\n\n# Coverage directory used by tools like istanbul\ncoverage\n\n# nyc test coverage\n.nyc_output\n\n# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)\n.grunt\n\n# Bower dependency directory (https://bower.io/)\nbower_components\n\n# node-waf configuration\n.lock-wscript\n\n# Compiled binary addons (https://nodejs.org/api/addons.html)\nbuild/Release\n\n# Dependency directories\nnode_modules/\njspm_packages/\n\n# TypeScript v1 declaration files\ntypings/\n\n# Optional npm cache directory\n.npm\n\n# Optional eslint cache\n.eslintcache\n\n# Optional REPL history\n.node_repl_history\n\n# Output of 'npm pack'\n*.tgz\n\n# Yarn Integrity file\n.yarn-integrity\n\n# dotenv environment variables file\n.env\n.env.test\n\n# parcel-bundler cache (https://parceljs.org/)\n.cache\n\n# next.js build output\n.next\n\n# nuxt.js build output\n.nuxt\n\n# vuepress build output\n.vuepress/dist\n\n# Serverless directories\n.serverless/\n\n# FuseBox cache\n.fusebox/\n\n# DynamoDB Local files\n.dynamodb/\n\n### OSX ###\n# General\n.DS_Store\n.AppleDouble\n.LSOverride\n\n# Icon must end with two \r\nIcon\n\n# Thumbnails\n._*\n\n# Files that might appear in the root of a volume\n.DocumentRevisions-V100\n.fseventsd\n.Spotlight-V100\nB\n.TemporaryItems\n.Trashes\n.VolumeIcon.icns\n.com.apple.timemachine.donotpresent\n\n# Directories potentially created on remote AFP share\n.AppleDB\n.AppleDesktop\nNetwork Trash Folder\nTemporary Items\n.apdisk\n\n#\n"
    },
    {
        name: 'package.json',
        data: "{\n  \"name\": \"ts-cli\",\n  \"version\": \"1.0.0\",\n  \"description\": \"NodeJS CLI using TypeScript\",\n  \"main\": \"./lib/index.js\",\n  \"bin\": {\n    \"ts-cli\": \"./lib/index.js\"\n  },\n  \"keywords\": [\n    \"cli\",\n    \"typescript\",\n    \"javascript\",\n    \"nodejs\"\n  ],\n  \"license\": \"MIT\",\n  \"scripts\": {\n    \"dev\": \"ts-node src/index.ts\",\n    \"build\": \"tsc -p .\"\n  },\n  \"devDependencies\": {\n    \"@types/node\": \"latest\",\n    \"ts-node\": \"latest\",\n    \"typescript\": \"latest\",\n    \"tslint\": \"latest\",\n    \"tslint-config-standard\": \"latest\"\n  }\n}\n"
    },
    {
        name: 'tsconfig.json',
        data: "{\n  \"compilerOptions\": {\n    \"target\": \"es5\",\n    \"module\": \"commonjs\",\n    \"lib\": [\"es6\", \"es2015\", \"dom\"],\n    \"declaration\": true,\n    \"outDir\": \"lib\",\n    \"rootDir\": \"src\",\n    \"strict\": true,\n    \"types\": [\"node\"],\n    \"esModuleInterop\": true,\n    \"resolveJsonModule\": true\n  }\n}\n"
    },
    {
        name: 'index.ts',
        data: "#!/usr/bin/env node\n\nconsole.log('you must edit src/index.ts to program your app');\n"
    },
    {
        name: 'tslint.json',
        data: "{\n  \"extends\": \"tslint-config-standard\",\n  \"rules\": {\n    \"semicolon\": [true, \"always\"],\n    \"indent\": [true, \"spaces\"],\n    \"ter-indent\": [true, 2],\n    \"space-before-function-paren\": [\"error\", {\n      \"anonymous\": \"always\",\n      \"named\": \"never\",\n      \"asyncArrow\": \"ignore\"\n    }]\n  }\n}\n"
    },
    {
        name: 'LICENSE',
        data: "MIT License\n\nCopyright (c) 2019 Author\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n"
    },
    {
        name: 'README.md',
        data: "# TS-CLI\nThis is a nodeJS CLI app written in TypeScript\n"
    }
];
